language: php
sudo: enabled

services:
  - docker

php:
  - '7.1'

before_install:
  - sudo apt-get update
  - sudo pip install docker-compose
  - docker-compose --version

script:
  - cp .env.dist .env
  - docker-compose up -d
  - docker exec -it xdevapi-php_php_1 "cd /var/www/ && composer install"
  - docker exec -it xdevapi-php_php_1 "/var/www/vendor/bin/phpunit -c /var/www/phpunit.xml"
  - docker stop $(docker ps -a -q)
