language: php
sudo: enabled

services:
  - docker

php:
  - '7.1'

before_install:
  - sudo apt-get update
  - sudo pip install docker-compose
  - docker-compose --version

script:
  - cp .env.dist .env
  - docker-compose build

