version: '3'
services:
  php:
      build: 'docker/php'
      restart: always
      volumes:
          - "./:/var/www/html"

  composer:
      image: "composer"
      volumes:
          - "./:/var/www/html"
      command: install

  mysqldb:
      image: mysql:${MYSQL_VERSION}
      container_name: ${MYSQL_HOST}
      restart: always
      env_file:
          - ".env"
      environment:
          - MYSQL_DATABASE=${MYSQL_DATABASE}
          - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
          - MYSQL_USER=${MYSQL_USER}
          - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      ports:
          - "8989:3306"
